package controlador;

public enum Evento {
	/* Primera cifra: modulo
	 * Segunda cifra: funcion
	 * (Tercera cifra: resultado funcion*/
	//CrearPlegaria
	CREARPLEGARIA(10),
	CREARPLEGARIAOK(100),
	CREARPLEGARIAFAIL(101),
	CREARPLEGARIAREACTIVACION(102),
	//BorrarPlegaria
	BORRARPLEGARIA(11),
	BORRARPLEGARIAOK(110),
	BORRARPLEGARIAFAIL(111),
	//ModificarPlegaria
	MODIFICARPLEGARIA(12),
	MODIFICARPLEGARIAOK(120),
	MODIFICARPLEGARIAFAIL(121),
	//MostrarPlegaria
	MOSTRARPLEGARIA(13),
	MOSTRARPLEGARIAOK(130),
	MOSTRARPLEGARIAFAIL(131),
	//MostrarPlegarias
	MOSTRARPLEGARIAS(14),
	MOSTRARPLEGARIASOK(140),
	
	//CrearCreyente
	CREARCREYENTE(20),
	CREARCREYENTEOK(200),
	CREARCREYENTEFAIL(201),
	CREARCREYENTEREACTIVACION(202),
	//BorrarCreyente
	BORRARCREYENTE(21),
	BORRARCREYENTEOK(210),
	BORRARCREYENTEFAIL(211),
	//ModificarCreyente
	MODIFICARCREYENTE(22),
	MODIFICARCREYENTEOK(220),
	MODIFICARCREYENTEFAIL(221),
	//MostrarCreyente
	MOSTRARCREYENTE(23),
	MOSTRARCREYENTEOK(230),
	MOSTRARCREYENTEFAIL(231),
	//MostrarCreyentes
	MOSTRARCREYENTES(24),
	MOSTRARCREYENTESOK(240),
	
	
	//CrearComentario
	CREARCOMENTARIO(30), //CrearEspecial
	CREARCOMENTARIOOK(300),
	CREARCOMENTARIOFAIL(301),
	//CumplirComentario
	CUMPLIRCOMENTARIO(31),
	CUMPLIRCOMENTARIOOK(310),
	CUMPLIRCOMENTARIOFAIL(311),
	//ModificarComentario
	MODIFICARCOMENTARIO(32),
	MODIFICARCOMENTARIOOK(320),
	MODIFICARCOMENTARIOFAIL(321),
	//MostrarComentarioPorCreyente
	MOSTRARCOMENTARIOPORCREYENTE(33),
	MOSTRARCOMENTARIOPORCREYENTEOK(330),
	MOSTRARCOMENTARIOPORCREYENTEFAIL(331),
	//MostrarComentarioPorPlegaria
	MOSTRARCOMENTARIOPORPLEGARIA(34),
	MOSTRARCOMENTARIOPORPLEGARIAOK(340),
	MOSTRARCOMENTARIOPORPLEGARIAFAIL(341),
	//Mostrar comentario 
	MOSTRARCOMENTARIO(35),
	MOSTRARCOMENTARIOOK(350),
	MOSTRARCOMENTARIOFAIL(351),
	
	
	
	//Eventos referentes a la interfaz grafica
	INICIALIZARMENU(5),
	ABRIRVISTAPLEGARIA(6),
	ABRIRVISTACREYENTE(7),
	
	ABRIRCREARPLEGARIA(40),
	ABRIRMODIFICARPLEGARIA(41),
	ABRIRCREARCREYENTE(42),
	ABRIRMODIFICARCREYENTE(43),
	ABRIRCREARCOMENTARIO(44),
	ABRIRMODIFICARCOMENTARIO(45)
	;
	
	
	private final int valor;
	
	Evento(int valor){
		this.valor = valor;
	}
	
	public int getValor(){return this.valor;}

}
